name: Create Release
on:
  push:
    branches:
      - master
      - main
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish version
        uses: actions/upload-artifact@v2
        with:
          name: v1.${{ env.GITHUB_RUN_ID }}
          path: ${{ github.workspace }}
